---
tags:
  - Productorder
description: Get a product order
responses:
  '200':
    description: Productorder information
    content:
      application/json:
        example:
        - id: 1
          orderId: 1
          productId: 1
          quantity: 2
          "@namespaces":
            store:
              name: /onlinestore/link-relations/
          "@controls":
            self:
              href: /api/productorders/1/
            profile:
              href: /profiles/productorder/
            collection:
              href: /api/productorders/
            store:get-order:
              method: GET
              title: Get product order for the productorder
              href: /api/order/1/
            store:get-product:
              method: GET
              title: Get product for the productorder
              href: /api/products/1/
            edit:
              method: PUT
              encoding: application/json
              title: Edit a product order
              schema:
                type: object
                properties:
                  orderId:
                    type: integer
                  productId:
                    type: integer
                  quantity:
                    type: integer
                required:
                  - orderId
                  - productId
                  - quantity
              href: /api/productorders/1/
            delete:
              method: DELETE
              title: Delete a product order
              href: /api/productorders/1/