---
tags:
  - Productorder
description: Update a productorder
requestBody:
  content:
    application/json:
      schema:
        type: object
        properties:
          orderId:
            type: integer
          productId:
            type: integer
          quantity:
            type: integer
        required:
          - orderId
          - productId
          - quantity
responses:
  '204':
    description: Productorder updated successfully
  '400':
    description: Invalid request body
  '404':
    description: Productorder not found
  '415':
    description: Unsupported media type