---
tags:
  - Productorder
description: Create a new product order
requestBody:
  content:
    application/json:
      schema:
        type: object
        properties:
          orderId:
            type: integer
          productId:
            type: integer
          quantity:
            type: integer
        required:
          - orderId
          - productId
          - quantity
responses:
  '201':
    description: Productorder created successfully
  '400':
    description: Invalid request body
  '404':
    description: Order or product not found
  '415':
    description: Request body must be JSON
