---
tags:
  - Productorder
description: Get the list of productorders
responses:
  '200':
    description: List of productorders
    content:
      application/json:
        example:
          "@namespaces":
            store:
              name: /onlinestore/link-relations/
          "@controls":
            self:
              href: /api/productorders/
            store:get-productorders:
              method: GET
              title: Get all products orders
              href: /api/productorders/
            store:add-productorder:
              method: POST
              encoding: application/json
              title: Add a new product order
              schema:
                type: object
                properties:
                  orderId:
                    type: integer
                  productId:
                    type: integer
                  quantity:
                    type: integer
                required:
                  - orderId
                  - productId
                  - quantity
              href: /api/productorders/
          productorders:
            - id: 1
              orderId: 1
              productId: 1
              quantity: 2
              "@controls":
                self:
                  href: /api/productorders/1/
                profile:
                  href: /profiles/productorder/
            - id: 2
              orderId: 1
              productId: 2
              quantity: 1
              "@controls":
                self:
                  href: /api/productorders/2/
                profile:
                  href: /profiles/productorder/